name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish to VSCode Extension Marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --cache ../.npm --prefer-offline

      - name: Publish to VSCode Extension Marketplace
        uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $VSCE_PAT"
        env:
          PUBLISHER_TOKEN: ${{ secrets.VSCE_PAT }}