name: Publish

on:
    push:
      branches:
        - main

jobs:
  publish:
    name: Publish to VSCode Extension Marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci --cache ../.npm --prefer-offline

      - name: Publish to VSCode Extension Marketplace
        run: npx vsce publish -p ${PUBLISHER_TOKEN}
        env:
          PUBLISHER_TOKEN: ${{ secrets.VSCE_PAT }}