name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to VSCode Extension Marketplace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline

      - name: Package the extension
        run: npm run build

      - name: Publish to VSCode Extension Marketplace
        run: npx vsce publish -p ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
