name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install

    - name: Increment version
      id: version
      run: |
        current_version=$(npm version patch)
        echo "new_version=$current_version" >> $GITHUB_ENV

    - name: Build the extension
      run: npm run build

    - name: Package the extension
      run: |
        npm run package
        ls -lh *.vsix

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: '*.vsix'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to Visual Studio Marketplace
      run: |
        vsce publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}

    - name: Commit and push version update
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add package.json
        git commit -m "ci: bump version to ${{ env.new_version }}"
        git tag ${{ env.new_version }}
        git push origin main --tags