name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest
    permissions: 
        contents: write
        issues: write
        pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci --cache ../.npm --prefer-offline

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release